# Header
menu:                      # Links in the navigation bar
  Home: /
#  Archives: /archives
  About: /about
  Medal: /medal
  Attributions: /attributions
#  Contribution: /contribution
  Description: /description
  Education: /education
#  Engineering: /engineering
#  Entrepreneurship: /entrepreneurship
#  Experiments: /experiments
#  Hardware: /hardware
  Human-Practices: /human-practices
#  Inclusivity: /inclusivity
#  Measurement: /measurement
  Members: /members
  Model: /model
#  Notebook: /notebook
#  Plant: /plant
  Results: /results
#  Safety-And-Security: /safety-and-security
  Software: /software
#  Sustainability: /sustainability

#rss: /atom.xml

home:
  style: default           # default, detail

favicon: /logo.png                  # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true                  # Display banner
  url: /banner.png                          # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 60                         # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color

# Personal info
avatar: /logo.png                            # Path to the avatar image relative to /source
author: iGEM Tainan
subtitle: The iGEM Team in Tainan
links:
  - name: Instagram
    icon: fa-brands fa-instagram      # Find icon codes at https://fontawesome.com/search
    url: https://www.instagram.com/igemncku/
#  - name: Steam
#    icon: fa-brands fa-steam
#    url: https://store.steampowered.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/iGEM-NCKU

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
#      - archive
#      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: false         # Enable Valine comment system
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
